cellar-web/src/main/java/eu/europa/ec/opoce/cellar/cmr/web/controller/admin/items/form/Filename.java
package eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form;

import com.google.common.base.MoreObjects;

import java.util.List;
import java.util.Objects;

/**
 * @author ARHS Developments
 */
public class Filename {

    private String cellarId;
    private List<String> pids;
    private String filename;
    private String suggestedFilename;
    private String existingFilename;
    private String version; // S3 file version on S3 (CMR_CELLAR_RESOURCE_MD.FILE)

    public Filename() {
    }

    public Filename(final String cellarId, final String filename, final String suggestedFilename,
                    final List<String> pids, final String version) {
        this.cellarId = cellarId;
        this.filename = filename;
        this.suggestedFilename = suggestedFilename;
        this.existingFilename = filename;
        this.pids = pids;
        this.version = version;
    }

    public String getCellarId() {
        return cellarId;
    }

    public void setCellarId(final String cellarId) {
        this.cellarId = cellarId;
    }

    public List<String> getPids() {
        return pids;
    }

    public String getPidsStr() {
        return String.join(",", pids);
    }

    public void setPids(final List<String> pids) {
        this.pids = pids;
    }

    public String getFilename() {
        return filename;
    }

    public void setFilename(final String filename) {
        this.filename = filename;
    }

    public String getSuggestedFilename() {
        return suggestedFilename;
    }

    public void setSuggestedFilename(final String suggestedFilename) {
        this.suggestedFilename = suggestedFilename;
    }

    public String getExistingFilename() {
        return existingFilename;
    }

    public void setExistingFilename(final String existingFilename) {
        this.existingFilename = existingFilename;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(final String version) {
        this.version = version;
    }

    public boolean filenameChanged() {
        return !Objects.equals(filename, existingFilename);
    }

    public boolean differFromSuggestion() {
        return !Objects.equals(filename, suggestedFilename);
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("cellarId", cellarId)
                .add("filename", filename)
                .toString();
    }
}

cellar-web/src/main/java/eu/europa/ec/opoce/cellar/cmr/web/controller/admin/items/form/FilenameForm.java
package eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form;

import com.google.common.base.MoreObjects;

import java.util.ArrayList;
import java.util.List;

/**
 * @author ARHS Developments
 */
public class FilenameForm {

    private List<Filename> filenames;

    public FilenameForm() {
        this(new ArrayList<>());
    }

    public FilenameForm(final List<Filename> filenames) {
        this.filenames = filenames;
    }

    public List<Filename> getFilenames() {
        return filenames;
    }

    public void setFilenames(final List<Filename> filenames) {
        this.filenames = filenames;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("filenames", filenames)
                .toString();
    }
}

cellar-web/src/main/java/eu/europa/ec/opoce/cellar/cmr/web/controller/admin/items/form/SearchForm.java
package eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form;

import com.google.common.base.MoreObjects;

/**
 * @author ARHS Developments
 */
public class SearchForm {

    private String identifier;
    private boolean filterIdenticalSuggestion = true;
    private int page = 1;

    public String getIdentifier() {
        return identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    public boolean isFilterIdenticalSuggestion() {
        return filterIdenticalSuggestion;
    }

    public void setFilterIdenticalSuggestion(boolean filterIdenticalSuggestion) {
        this.filterIdenticalSuggestion = filterIdenticalSuggestion;
    }

    public int getPage() {
        return page;
    }

    public void setPage(int page) {
        this.page = page;
    }

    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this)
                .add("identifier", identifier)
                .add("filterIdenticalSuggestion", filterIdenticalSuggestion)
                .add("page", page)
                .toString();
    }
}

cellar-web/src/main/java/eu/europa/ec/opoce/cellar/cmr/web/controller/admin/items/ItemFilenameController.java
package eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items;

import eu.europa.ec.opoce.cellar.cl.controller.AbstractCellarController;
import eu.europa.ec.opoce.cellar.cl.controller.message.ICellarUserMessage;
import eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form.Filename;
import eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form.FilenameForm;
import eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.form.SearchForm;
import eu.europa.ec.opoce.cellar.cmr.web.controller.admin.items.service.ItemFilenameService;
import eu.europa.ec.opoce.cellar.common.util.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.util.List;

/**
 * @author ARHS Developments
 */
@Controller
public class ItemFilenameController extends AbstractCellarController {

    private static final Logger LOGGER = LoggerFactory.getLogger(ItemFilenameController.class);
    public static final String PAGE_URL = "/items";
    private static final String JSP_NAME = "items";
    private static final String SEARCH_FORM = "search_form";
    private static final String FILENAME_FORM = "filename_form";

    private final ItemFilenameService itemFilenameService;

    @Autowired
    public ItemFilenameController(final ItemFilenameService itemFilenameService) {
        this.itemFilenameService = itemFilenameService;
    }

    @RequestMapping(value = ItemFilenameController.PAGE_URL,method = RequestMethod.GET)
    public String home(final ModelMap model) {
        model.addAttribute(SEARCH_FORM, new SearchForm());
        return JSP_NAME;
    }

    @RequestMapping(value = ItemFilenameController.PAGE_URL+"/search",method = RequestMethod.POST)
    public String search(final @ModelAttribute(SEARCH_FORM) SearchForm searchForm,
                         final BindingResult bindingResult,
                         final ModelMap model) {
        LOGGER.debug("Searching for items of '{}'", searchForm);
        model.addAttribute(SEARCH_FORM, searchForm);

        if (StringUtils.isBlank(searchForm.getIdentifier())) {
            super.addUserMessage(ICellarUserMessage.LEVEL.ERROR, "items.message.empty", "Identifier is empty");
            return JSP_NAME;
        }

        try {
            final List<Filename> filenames = getFilenames(searchForm);
            model.addAttribute(FILENAME_FORM, new FilenameForm(filenames));
        } catch (IllegalArgumentException e) {
            super.addUserMessage(ICellarUserMessage.LEVEL.ERROR, "items.message.not-found", "Not found");
        }

        return JSP_NAME;
    }

    private List<Filename> getFilenames(final SearchForm searchForm) {
        final String id = searchForm.getIdentifier();

        if (searchForm.isFilterIdenticalSuggestion()) {
            return itemFilenameService.getFilteredFilenames(id, searchForm.getPage());
        } else {
            return itemFilenameService.getFilenames(id, searchForm.getPage());
        }
    }

    @RequestMapping(value = ItemFilenameController.PAGE_URL+"/save",method = RequestMethod.POST)
    public String save(final @ModelAttribute(FILENAME_FORM) FilenameForm filenameForm,
                       final ModelMap model) {
        LOGGER.debug("Saving filenames: ", filenameForm.getFilenames());
        model.addAttribute(SEARCH_FORM, new SearchForm());
        model.addAttribute(FILENAME_FORM, filenameForm);

        try {
            final List<Filename> updatedFilenames = itemFilenameService.updateItemFilenames(filenameForm.getFilenames());
            filenameForm.getFilenames().removeAll(updatedFilenames);

            super.addUserMessage(ICellarUserMessage.LEVEL.SUCCESS, "items.message.success", "Success");
        } catch (Exception e) {
            super.addUserMessage(ICellarUserMessage.LEVEL.ERROR, null, e.getMessage());
        }

        return JSP_NAME;
    }

}

cellar-web/src/main/webapp/WEB-INF/jsp/admin/items/items.jsp
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="app" tagdir="/WEB-INF/tags" %>

<script type="text/javascript" src="${pageContext.request.contextPath}/resources/admin/items/js/items.js"></script>
<link rel="stylesheet" href="${pageContext.request.contextPath}/resources/admin/items/css/items.css" type="text/css"/>

<div class="dashboard" id="items">

    <!-- Title -->
    <div class="title">
        <spring:message code="items.title"/>
    </div>

    <!-- Search form -->
    <form:form method="POST" action="${base}/admin/items/search" modelAttribute="search_form" cssClass="search">
        <form:label path="identifier" for="identifier">
            <fmt:message key="items.search.identifier.label"/>
            <fmt:message key="items.search.identifier.placeholder" var="placeholder"/>
            <form:input id="identifier" path="identifier" placeholder="${placeholder}" style="min-width: 350px" autofocus="autofocus"/>
        </form:label>

        <form:label path="filterIdenticalSuggestion" for="filterIdenticalSuggestion">
            <fmt:message key="items.search.filter.label"/>
            <form:checkbox id="filterIdenticalSuggestion" path="filterIdenticalSuggestion" />
        </form:label>

        <form:input id="page" path="page" value="${search_form.page}" type="hidden" />

        <input type="submit" value="<fmt:message key="items.search.button" />"/>
    </form:form>

    <!-- Update form -->
    <c:if test="${filename_form != null}">
        <form:form method="POST" action="${base}/admin/items/save" modelAttribute="filename_form">

            <!-- Table -->
            <table>
                <!-- Header -->
                <tr>
                    <th><fmt:message key="items.table.psi"/></th>
                    <th><fmt:message key="items.table.identifiers"/></th>
                    <th><fmt:message key="items.table.filename"/></th>
                    <th><fmt:message key="items.table.suggestion"/></th>
                </tr>

                <!-- Rows -->
                <c:forEach items="${filename_form.filenames}" var="filename" varStatus="status">
                    <tr>
                        <td>
                            <button id="plusButton" data-id="psi-${filename.cellarId}">+</button>
                        </td>
                        <td>
                            <span style="white-space: nowrap;">
                                <a target="_blank" href=<c:url value="/admin/search/content?cellarId=${filename.cellarId}"/>>
                                    ${filename.cellarId}
                                </a>
                            </span>
                            <ul id="psi-${filename.cellarId}" class="psi-hidden">
                                <c:forEach items="${filename.pids}" var="pid">
                                    <li>${pid}</li>
                                </c:forEach>
                            </ul>
                        </td>
                        <td>
                            <form:input id="filename-${filename.cellarId}"
                                        type="text"
                                        path="filenames[${status.index}].filename"
                                        value="${filename.filename}"
                            />
                        </td>
                        <td align="right">
                                ${filename.suggestedFilename}
                            <button id="useButton" class="replace-btn" data-file-id="filename-${filename.cellarId}" data-suggested-file-id="${filename.suggestedFilename}">
                                <fmt:message key="items.table.use-filename"/>
                            </button>
                        </td>
                    </tr>

                    <form:input type="hidden" path="filenames[${status.index}].cellarId" value="${filename.cellarId}"/>
                    <form:input type="hidden" path="filenames[${status.index}].pids" value="${filename.pidsStr}"/>
                    <form:input type="hidden" path="filenames[${status.index}].existingFilename"
                                value="${filename.existingFilename}"/>
                    <form:input type="hidden" path="filenames[${status.index}].suggestedFilename"
                                value="${filename.suggestedFilename}"/>
                    <form:input type="hidden" path="filenames[${status.index}].version" value="${filename.version}"/>
                </c:forEach>
            </table>

            <!-- Pagination -->
            <div style="float: right;">
                <c:if test="${search_form.page > 1}">
                    <button type="button" id="previousButton" data-current-page="${search_form.page}">
                        <fmt:message key="items.message.previous" />
                    </button>
                </c:if>
                <c:if test="${filename_form.filenames.size() >= 25}">
                    <button type="button" id="nextButton" data-current-page="${search_form.page}">
                        <fmt:message key="items.message.next" />
                    </button>
                </c:if>
            </div>

            <!-- Submit -->
            <button type="button" id="replaceAllButton">
                    <fmt:message key="items.table.replace-all" />
            </button>
            <input type="submit" style="background: #92C1F0" value="<fmt:message key="items.table.save-all" />"/>

        </form:form>
    </c:if>
</div>